### ISSUE TITLE
freeze columns towards the end of the grid

### ISSUE THREAD

**Issue by Sax-Yusuph** [glideapps/glide-data-grid#522] opened 2022-10-04 11:54 UTC
Hi, 
is it possible to have the column freeze on the right side as well? 

![image](https://user-images.githubusercontent.com/57273445/193813132-8ab1a27d-ca9e-4a5e-93de-d09b72d09df7.png)

**Comment by jassmith** [comment] 2022-10-04 13:45
Duplicate of #469

**Closed** 2022-10-04 13:45 UTC
