### ISSUE TITLE
Stretch columns to fit width

### ISSUE THREAD

**Issue by infinitepr0** [glideapps/glide-data-grid#259] opened 2022-04-12 06:22 UTC
Is it possible to stretch the columns (evenly) to fill the width of the parent container?
Also, how do you remove the empty column at the end of the grid?

**Comment by jassmith** [comment] 2022-04-12 17:47
Empty column? You mean the leftover space if your columns are not wide enough to fill?

There is no built in fill mode. I considered adding it but it adds a lot of extra work. Let me see if I can come up with a simple solution.

**Comment by amiregelz** [comment] 2022-06-20 08:19
@jassmith We ran into this issue as well, is it complicated to add support for percentage width? 🙏

**Comment by jassmith** [comment] 2022-06-20 16:21
The problem is how this interacts with resizing. I think they are basically mutually exclusive.

**Comment by jassmith** [comment] 2022-06-20 18:56
Im struggling to imagine the dynamic model here, as you resize elements all the percentage elements sizes change which changes the start position of the column which creates an unintended resize delta on your next mouse motion. The only realistic solution here seems to be that resizing columns should "lock" percentage columns at their current size for the duration of the resize.

**Comment by jassmith** [comment] 2022-06-21 04:07
Fixed by #406 but there is still work to be done

**Comment by jassmith** [comment] 2022-06-21 04:07
You can see the oddball behavior with the resizing I was talking about.

**Comment by amiregelz** [comment] 2022-06-21 21:38
@jassmith If I don't allow resizing, can I define columns width in percentage? Is it supported?

**Closed** 2022-06-23 22:30 UTC
Labels: feature request
