### ISSUE TITLE
SyntaxError: Unexpected token '.'  (image-overlay-editor)

### ISSUE THREAD

**Issue by raphkhan** [glideapps/glide-data-grid#14] opened 2021-01-19 17:43 UTC
I have the following error when trying to use the DataEditor component in my NextJS project. The error tells me there is an `unexpected token '.'` in a file inside the nodes_modules folder.

Yet, I tried to use this component in a new React project, in order to see if I have the same error, and everything works well.

How can I fix it in my NextJS project?

Thanks for your answer!

<img width="1064" alt="Capture d’écran 2021-01-19 à 19 36 18" src="https://user-images.githubusercontent.com/65778231/105072389-6d449880-5a8e-11eb-989e-902938564909.png">

**Comment by jassmith** [comment] 2021-01-21 21:00
That line is 

`require("react-responsive-carousel/lib/styles/carousel.min.css");`

I suspect the file is being tree-shook out. Can you make sure it is properly included in your deployment?

**Comment by jassmith** [comment] 2021-01-24 21:25
Closing as duplicate of #18

**Closed by jassmith** 2021-01-24 21:25 UTC
Labels: question
