### ISSUE TITLE
Smooth scroll with freezeColumns animation jank

### ISSUE THREAD

**Issue by twobit** [glideapps/glide-data-grid#171] opened 2022-02-11 23:20 UTC
There's a slightly disorienting animation when smooth scroll and freezeColumns are enabled:

https://user-images.githubusercontent.com/2778/153683635-05f7a11b-6ede-4825-ae59-66b1a943e173.mov

Safari: 15.4
macOS: 12.3

**Comment by ivoelbert** [comment] 2022-02-12 23:11
Looks like a Safari only bug (wow! who would've guessed that 🙄).

Apart from that, by looking at this in Chrome and Firefox I noticed that we're dropping a lot of frames when the shadow animation happens.

Thanks for reporting!

**Comment by jassmith** [comment] 2022-02-12 23:25
Shadow animations causing jank... say it aint so :P

**Comment by bryhasagithub** [comment] 2022-02-15 23:35
was able to reproduce on safari as well

**Comment by jassmith** [comment] 2022-02-15 23:54
Fixed in main

**Closed by jassmith** 2022-02-15 23:54 UTC
Labels: bug, IE6
