### ISSUE TITLE
Issues with grid borders in Safari 16

### ISSUE THREAD

**Issue by pzcfg** [glideapps/glide-data-grid#500] opened 2022-09-21 22:19 UTC
We've noticed with the latest version of Safari (16.0) that if `bgHeader` is set the grid borders seem to disappear entirely. When this is is not set the borders still seem to be fainter than in other browsers.

| `bgHeader` | Chrome | Safari 15.6 | Safari 16.0 |
|-|-|-|-|
| not set | <img width="1387" alt="No bgHeader Chrome" src="https://user-images.githubusercontent.com/94077014/191620213-cb5c0034-8f24-44b4-a44f-9de5894b3ec2.png"> | <img width="1311" alt="No bgHeader Safari 15.6" src="https://user-images.githubusercontent.com/94077014/191620268-54e5168e-4f25-4980-82ab-ceb79220ed9e.png"> | <img width="1312" alt="No bgHeader Safari 16.0" src="https://user-images.githubusercontent.com/94077014/191620327-1be5c4fd-0eb6-421d-9224-92148cd23ff3.png"> |
| `'#FFFFFF'` | <img width="1397" alt="bgHeader #FFFFFF Chrome" src="https://user-images.githubusercontent.com/94077014/191620408-3e3b97bd-6337-41f6-9285-5f779103e80a.png"> | <img width="1320" alt="bgHeader #FFFFFF Safari 15.6" src="https://user-images.githubusercontent.com/94077014/191620442-0f7d57bd-002a-4589-9f5b-dea76caac86d.png"> | <img width="1312" alt="bgHeader #FFFFFF Safari 16.0" src="https://user-images.githubusercontent.com/94077014/191620485-d6a32bc1-ab51-4c56-be1b-0c7e7555e7e7.png"> |

**Comment by jassmith** [comment] 2022-09-25 03:41
This is the part where we pray safari 16 didn't fuck up clipping...

**Comment by jassmith** [comment] 2022-09-25 03:43
Can you see if anything changes if you change the values of experimental.renderStrategy?

**Comment by jassmith** [comment] 2022-09-30 01:48
We are unable to reproduce this issue, our best guess is you are using some kind of beta browser? Closing until you can provide better reproduction information.

**Closed by jassmith** 2022-09-30 01:48 UTC
