### ISSUE TITLE
Feature Request: SubRow Functionality

### ISSUE THREAD

**Issue by pedro757** [glideapps/glide-data-grid#866] opened 2024-01-12 21:03 UTC
Like tanstack subrows https://tanstack.com/table/v8/docs/api/core/row#subrows

see this sandbox https://codesandbox.io/p/sandbox/tanstack-subrows-indeterminate-issue-dfg1lh?file=%2Fsrc%2FApp.tsx

**Comment by jassmith** [comment] 2024-01-13 03:59
Duplicate of #823

**Closed by jassmith** 2024-01-13 03:59 UTC
Labels: type:enhancement
