### ISSUE TITLE
Access to onChange in cell

### ISSUE THREAD

**Issue by dawidbak** [glideapps/glide-data-grid#382] opened 2022-06-14 11:39 UTC
Hi, is it possible to get the property onChange in the cell where the user is currently editing? I care to add formatting but don't know how to do it. I came across `https://github.com/glideapps/glide-data-grid/blob/main/packages/core/API.md#provideeditor` but honestly don't really know how to implement it

**Comment by jassmith** [comment] 2022-06-19 18:22
Duplicate of #392 

I realize your report was first but I already put my thoughts over there. It would be great if you could chime in if the proposed solution works for you too.

**Closed by jassmith** 2022-06-19 18:22 UTC
