### ISSUE TITLE
Unable to make deletion work with custom rendered cell

### ISSUE THREAD

**Issue by tb-viktor** [glideapps/glide-data-grid#578] opened 2022-12-20 09:06 UTC
Hi,

First of all, thank you for open sourcing this great library. We are in the process of integrating it into our product and have a problem with making a custom cell work the way we want.

We wrote our own custom dropdown/autocomplete component, but using the keyboard delete/backspace key does not remove the current value like in regular cells, nor trigger the `onDelete` or `deletedValue` blocks in it. We find the documentation quite lacking in this area, but I noticed that in the official example with `@glideapps/glide-data-grid-cells` it does not work either (https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cell-editing).

We declared the cell this way:

```
{
  kind: GridCellKind.Custom,
  allowOverlay: true,
  copyData: cellDataValue === null ? '' : String(cellDataValue),
  data: {
    kind: 'viktor-dropdown',
    options: columnOptions,
    value: cellDataValue,
    autocomplete: columnType === 'autocomplete',
  },
}
```

And the custom renderer like this:

```
customRenderers={[
  {
    kind: GridCellKind.Custom,
    isMatch: (cell): cell is CustomCell<IViktorDropdownCellData> =>
      (cell as CustomCell<IViktorDropdownCellData>).data.kind === 'viktor-dropdown',
    provideEditor: () => ({
      editor: Dropdown,
      disablePadding: true,
      deletedValue: (toDelete) => ({
        ...toDelete,
        copyData: '',
        data: {
          ...toDelete.data,
          value: null,
        },
      }),
    }),
    draw: (args, cell) => {
      ...
    },
    onPaste: (value, cellData) => ({
      ...cellData.data,
      value,
    }),
    onDelete: (cell) => ({
      ...cell,
      data: {
        ...cell.data,
        value: null,
      },
    }),
  },
]}
```

It works well apart from it not doing anything when we highlight the cell and press delete. Is there some piece of configuration we are missing?

**Comment by pzcfg** [comment] 2022-12-21 21:40
I'm not too familiar with the codepaths for this, but I think the problem is that this
```
if (cellValue.kind === GridCellKind.Custom)
```
condition prevents the
```
const toDelete = getCellRenderer(cellValue);
newVal = toDelete?.onDelete?.(cellValue);
```
below from being called.

https://github.com/glideapps/glide-data-grid/blob/6bde16e0cc9a6b849efdaeac6e65d7de8b1b269a/packages/core/src/data-editor/data-editor.tsx#L2672-L2702

Further down the grid's `onDelete` prop gets called
```
if (isDeleteKey) {
  const callbackResult = onDelete?.(gridSelection) ?? true;
```
but this seems to still skip over any `onDelete`s passed to `customRenderers`

**Comment by flash2k2** [comment] 2023-01-08 13:52
Modifying
`if (cellValue.kind === GridCellKind.Custom) {
                                const editor = provideEditor?.(cellValue);
                                if (isObjectEditorCallbackResult(editor)) {
                                    newVal = editor?.deletedValue?.(cellValue);
                                }
                            }`
to
`if (cellValue.kind === GridCellKind.Custom) {
                                const toDelete = getCellRenderer(cellValue);
                                const editor = toDelete?.provideEditor?.(cellValue);
                                if (isObjectEditorCallbackResult(editor)) {
                                    newVal = editor?.deletedValue?.(cellValue);
                                }
                            }`

fixes for me.

Sorry, don't know how to format the code.

**Comment by jassmith** [comment] 2023-01-11 03:27
@flash2k2 thanks for identifying the fix.

**Comment by jassmith** [comment] 2023-01-11 16:29
I guess I misunderstand, there is a belief the bug is in core? I'm sorry it's a big project and I am one man, I may have misunderstood here.

**Comment by tb-viktor** [comment] 2023-01-11 16:33
Yes, indeed. What the guys wrote above concerns code inside `glide-data-grid/packages/core/src/data-editor/data-editor.tsx`.

It does not seem to be an issue with our implementation. It also happens in storybook here: https://glideapps.github.io/glide-data-grid/?path=/story/extra-packages-cells--custom-cell-editing. It is not possible to delete values from custom cells whether they are from the extra package or self-made.

**Comment by jassmith** [comment] 2023-01-11 16:34
Thanks will address shortly

**Comment by jassmith** [comment] 2023-01-16 02:53
Fixed in main :)

**Closed by jassmith** 2023-01-16 02:53 UTC

**Comment by homanp** [comment] 2023-03-01 19:09
I'm facing the same issue, `onDelete` or `deleteValue` do nothing on custom cell I created. Paste works but not delete. Is there something specific that needs to be added to the renderer @jassmith ?

**Comment by Tibfib** [comment] 2023-03-02 23:45
also experiencing this and would appreciate an update to the npm package :)

**Comment by Tibfib** [comment] 2023-05-10 20:46
Update: you can use the beta tag they published!

`@glideapps/glide-data-grid@5.2.2-beta3`
